=== Facquet/VHDL-RC/sonar-vhdlrc-plugin/src/test/files/handbooks/VHDL_Handbook_STD-master/XSD/handbook.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="HANDBOOK" xmlns:xs="http://www.w3.org/2001/XMLSchema" 
 	elementFormDefault="qualified" xmlns:hb="HANDBOOK">
    <!-- ======================= -->
    <!--    Element definition   -->
    <!-- ======================= -->
    <xs:element name="RuleSet" type="hb:TRuleSet"/>
    <!-- ======================= -->
    <!-- Complex type definition -->
    <!-- ======================= -->
    <xs:complexType name="TRuleSet">
        <xs:sequence>
            <xs:element name="Rule" type="hb:TRule" maxOccurs="unbounded" minOccurs="1"/>
            <xs:element name="RuleSetHist" type="hb:TRuleSetHist" maxOccurs="1" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TRuleSetHist">
        <xs:sequence>
            <xs:element name="Version" type="xs:positiveInteger" maxOccurs="1" minOccurs="1"/>
            <xs:element name="Creation" type="xs:date" maxOccurs="1" minOccurs="1"/>
            <xs:element name="Modified" type="xs:date" maxOccurs="1" minOccurs="1"/>
            <xs:element name="Revision" type="xs:string" maxOccurs="1" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TRule">
        <xs:sequence>
            <xs:element name="RuleUID" maxOccurs="1" minOccurs="1">
                <xs:simpleType>
                    <xs:restriction base="xs:ID">
                        <xs:pattern value="[A-Z]{3}_[0-9]{5}" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="RuleHist" type="hb:TRuleHist"	maxOccurs="1" minOccurs="1"/>
            <xs:element name="RuleContent" type="hb:TRuleContent" maxOccurs="1" minOccurs="1"/>
            <xs:element name="Sonarqube" type="hb:TSonarqube" maxOccurs="1" minOccurs="0"/>
            <xs:element name="RuleDesc" type="hb:TRuleDesc"	maxOccurs="1" minOccurs="0"/>
            <xs:element name="RuleParams" type="hb:TRuleParams" maxOccurs="1" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="UID" type="hb:TRuleUID"/>
    </xs:complexType>
    <xs:complexType name="TRuleHist">
        <xs:sequence>
            <xs:element name="Status" type="hb:EnumRuleStatus" maxOccurs="1" minOccurs="1"/>
            <xs:element name="Version" type="xs:positiveInteger" maxOccurs="1" minOccurs="1"/>
            <xs:element name="Creation" type="xs:date" maxOccurs="1" minOccurs="1"/>
            <xs:element name="Modified" type="xs:date" maxOccurs="1" minOccurs="1"/>
            <xs:element name="Revision" type="xs:string" maxOccurs="1" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TRuleContent">
        <xs:sequence>
            <xs:element name="Name" type="xs:string" maxOccurs="1" minOccurs="1"/>
            <xs:element name="IsParent" type="xs:boolean" maxOccurs="1" minOccurs="1"/>
            <xs:element name="IsSon" type="xs:boolean" maxOccurs="1" minOccurs="1"/>
            <xs:element name="ParentUID" type="hb:TRuleUID" maxOccurs="1" minOccurs="1" nillable="true"/>
            <xs:element name="Technology" type="hb:EnumTech" maxOccurs="1" minOccurs="1"/>
            <xs:element name="ApplicationFields" type="hb:ListAppliFields" maxOccurs="1" minOccurs="1"/>
            <xs:element name="Category" type="hb:EnumCat" maxOccurs="1"	minOccurs="1"/>
            <xs:element name="SubCategory" type="hb:EnumSubCat"	maxOccurs="1" minOccurs="1"/>
            <xs:element name="Severity" type="hb:EnumSeverity" maxOccurs="1" minOccurs="1"/>
            <xs:element name="Rationale" type="xs:string" maxOccurs="1"	minOccurs="1"/>
            <xs:element name="ShortDesc" type="xs:string" maxOccurs="1"	minOccurs="1"/>
            <xs:element name="LongDesc" type="xs:string" maxOccurs="1" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TSonarqube">
        <xs:sequence>
			<xs:element name="SonarType" type="hb:EnumSonarType" maxOccurs="1" minOccurs="1" />
            <xs:element name="SonarSeverity" type="hb:EnumSonarSeverity" maxOccurs="1" minOccurs="1"/>			
            <xs:element name="RemediationEffort" type="hb:EnumEffort" maxOccurs="1" minOccurs="1"/>
            <xs:element name="SonarTag" type="hb:EnumTag" maxOccurs="1" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TRuleDesc">
        <xs:sequence>
            <xs:element name="GoodExDesc" type="xs:string" maxOccurs="1" minOccurs="1" nillable="true"/>
            <xs:element name="GoodExample" type="xs:string"	maxOccurs="1" minOccurs="1" nillable="true"/>
            <xs:element name="BadExDesc" type="xs:string" maxOccurs="1"	minOccurs="1" nillable="true"/>
            <xs:element name="BadExample" type="xs:string" maxOccurs="1" minOccurs="1" nillable="true"/>
            <xs:element name="FigureDesc" type="xs:string" maxOccurs="1" minOccurs="1" nillable="true"/>
            <xs:element name="Figure" type="hb:TFigure" maxOccurs="1" minOccurs="1" nillable="true"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TFigure">
        <xs:attribute name="fileref" type="xs:anySimpleType"/>
        <xs:attribute name="height" type="xs:string"/>
        <xs:attribute name="width" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="TRuleParams">
        <xs:sequence>
            <xs:element name="IntParam" type="hb:TIntParam" maxOccurs="unbounded" minOccurs="0" />
            <xs:element name="StringParam" type="hb:TStringParam" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element name="RangeParam" type="hb:TRangeParam" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TIntParam">
        <xs:sequence>
            <xs:element name="ParamID" type="hb:TParamID" maxOccurs="1" minOccurs="1"/>
            <xs:element name="Relation" type="hb:EnumRelation" maxOccurs="1" minOccurs="1"/>
            <xs:element name="Value" type="xs:positiveInteger" maxOccurs="1" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TStringParam">
        <xs:sequence>
            <xs:element name="ParamID" type="hb:TParamID" maxOccurs="1" minOccurs="1"/>
            <xs:element name="Position" type="hb:EnumPosition" maxOccurs="1" minOccurs="1"/>
            <xs:element name="Value" type="xs:string" maxOccurs="1" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TRangeParam">
        <xs:sequence>
            <xs:element name="ParamID" type="hb:TParamID" maxOccurs="1" minOccurs="1"/>
            <xs:element name="Range" type="hb:EnumRange" maxOccurs="1" minOccurs="1"/>
            <xs:element name="ValueMin" type="xs:integer" maxOccurs="1" minOccurs="1"/>
            <xs:element name="ValueMax" type="xs:integer" maxOccurs="1" minOccurs="1"/>
        </xs:sequence>
<!--    <xs:assert test="@ValueMax > @ValueMin"/> -->
    </xs:complexType>
    <!-- ======================= -->
    <!-- Simple type definition  -->
    <!-- ======================= -->
    <xs:simpleType name="TRuleUID">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{3}_[0-9]{5}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="TParamID">
        <xs:restriction base="xs:string">
            <xs:pattern value="P[0-9]+"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="EnumRuleStatus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Draft"/>
            <xs:enumeration value="In progress"/>
            <xs:enumeration value="Release candidate"/>
            <xs:enumeration value="Validated"/>
            <xs:enumeration value="Rejected"/>
            <xs:enumeration value="Active"/>
            <xs:enumeration value="Deleted"/>
            <xs:enumeration value="To be discussed"/>
            <xs:enumeration value="Modified"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="EnumTech">
        <xs:restriction base="xs:string">
            <xs:enumeration value="FPGA"/>
            <xs:enumeration value="ASIC"/>
            <xs:enumeration value="VLSI"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="EnumCat">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Traceability"/>
            <xs:enumeration value="Formatting"/>
            <xs:enumeration value="Design"/>
            <xs:enumeration value="Simulation"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="EnumSubCat">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Versioning"/>
            <xs:enumeration value="Reuse"/>
            <xs:enumeration value="Requirement"/>
            <xs:enumeration value="Miscellaneous"/>
            <xs:enumeration value="Naming"/>
            <xs:enumeration value="FileStructure"/>
            <xs:enumeration value="StateMachine"/>
            <xs:enumeration value="Reset"/>
            <xs:enumeration value="Clocking"/>
            <xs:enumeration value="I/O"/>
            <xs:enumeration value="Synchronous"/>
            <xs:enumeration value="Combinational"/>
            <xs:enumeration value="Type"/>
            <xs:enumeration value="Reliability"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="EnumSeverity">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Note"/>
            <xs:enumeration value="Minor"/>
            <xs:enumeration value="Major"/>
        </xs:restriction>
    </xs:simpleType>
	<xs:simpleType name="EnumSonarType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Vulnerability"/>
			<xs:enumeration value="Bug"/>
			<xs:enumeration value="Code_Smell"/>
		</xs:restriction>
	</xs:simpleType>
    <xs:simpleType name="EnumEffort">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Trivial"/>
            <xs:enumeration value="Easy"/>
            <xs:enumeration value="Medium"/>
            <xs:enumeration value="Major"/>
            <xs:enumeration value="High"/>
            <xs:enumeration value="Complex"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="EnumTag">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Brain-overload"/>
            <xs:enumeration value="Bad-practice"/>
            <xs:enumeration value="Bug"/>
            <xs:enumeration value="Clumsty"/>
            <xs:enumeration value="Confusing"/>
            <xs:enumeration value="Convention"/>
            <xs:enumeration value="Design"/>
            <xs:enumeration value="Lock-in"/>
            <xs:enumeration value="Pittfall"/>
            <xs:enumeration value="Security"/>
            <xs:enumeration value="Suspicious"/>
            <xs:enumeration value="Unpredictable"/>
            <xs:enumeration value="Unused"/>
            <xs:enumeration value="User-experience"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="EnumSonarSeverity">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Blocker"/>
            <xs:enumeration value="Critical"/>
            <xs:enumeration value="Major"/>
            <xs:enumeration value="Minor"/>
            <xs:enumeration value="Info"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="EnumRelation">
        <xs:restriction base="xs:string">
            <xs:enumeration value="LT"/>
            <xs:enumeration value="LET"/>
            <xs:enumeration value="E"/>
            <xs:enumeration value="GET"/>
            <xs:enumeration value="GT"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="EnumPosition">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Prefix"/>
            <xs:enumeration value="Contain"/>
            <xs:enumeration value="Equal"/>
            <xs:enumeration value="Suffix"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="EnumRange">
        <xs:restriction base="xs:string">
            <xs:enumeration value="LT_GT"/>
            <xs:enumeration value="LET_GT"/>
            <xs:enumeration value="LET_GET"/>
            <xs:enumeration value="LT_GET"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="ListAppliFields">
        <xs:list itemType="hb:EnumAppliFieds"/>
    </xs:simpleType>
    <xs:simpleType name="EnumAppliFieds">
        <xs:restriction base="xs:string">
            <xs:enumeration value="General"/>
            <xs:enumeration value="Spatial"/>
            <xs:enumeration value="Avionic"/>
            <xs:enumeration value="Nuclear"/>
            <xs:enumeration value="Railway"/>
            <xs:enumeration value="Defense"/>
            <xs:enumeration value="Telecom"/>
            <xs:enumeration value="Media"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Facquet/VHDL-RC/sonar-vhdlrc-plugin/src/test/parameters/hbs/handbook_string_param.xml
<?xml version="1.0" encoding="UTF-8"?>
<hb:RuleSet xmlns:hb="HANDBOOK"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="HANDBOOK ../XSD/handbook.xsd ">

	<hb:Rule UID="CNE_01200">
		<hb:RuleUID>CNE_01200</hb:RuleUID>
		<hb:RuleHist>
			<hb:Status>Validated</hb:Status>
			<hb:Version>4</hb:Version>
			<hb:Creation>2014-09-30</hb:Creation>
			<hb:Modified>2015-07-16</hb:Modified>
			<hb:Revision>
				V1 : 2014-09-30 : Creation
				V2 : 2014-12-01 : Status ; Name ; Rationale 
				V3 : 2015-02-17 : Technology
				V4 : 2015-07-16 : GoodExample ; BadExample ; GoodExDesc ; BadExDesc
			</hb:Revision>
		</hb:RuleHist>
		<hb:RuleContent>
			<hb:Name>Identification of process label</hb:Name>
			<hb:IsParent>false</hb:IsParent>
			<hb:IsSon>true</hb:IsSon>
			<hb:ParentUID>STD_00100</hb:ParentUID>
			<hb:Technology>VLSI</hb:Technology>
			<hb:ApplicationFields>General</hb:ApplicationFields>
			<hb:Category>Formatting</hb:Category>
			<hb:SubCategory>Naming</hb:SubCategory>
			<hb:Severity>Minor</hb:Severity>
			<hb:Rationale>Differentiating process label from other VHDL object improves readability.</hb:Rationale>
			<hb:ShortDesc>Process label name starts by a prefix: "P_".</hb:ShortDesc>
			<hb:LongDesc>No additional information.</hb:LongDesc>
		</hb:RuleContent>
		<hb:RuleDesc>
			<hb:GoodExDesc>Extracted from CNE_01200_good.vhd</hb:GoodExDesc>
			<hb:GoodExample >CNE_01200_good</hb:GoodExample>
			<hb:BadExDesc>Extracted from CNE_01200_bad.vhd</hb:BadExDesc>
			<hb:BadExample >CNE_01200_bad</hb:BadExample>
			<hb:FigureDesc />
			<hb:Figure />
		</hb:RuleDesc>
		<hb:RuleParams>
			<hb:StringParam>
			   <hb:ParamID>P1</hb:ParamID>
			   <hb:Position>Prefix</hb:Position>
			   <hb:Value>p_</hb:Value>
		   </hb:StringParam>
	   </hb:RuleParams>
	</hb:Rule>
	
	<hb:Rule UID="STD_00300">
		<hb:RuleUID>STD_00300</hb:RuleUID>
		<hb:RuleHist>
			<hb:Status>Active</hb:Status>
			<hb:Version>6</hb:Version>
			<hb:Creation>2014-09-30</hb:Creation>
			<hb:Modified>2017-11-24</hb:Modified>
			<hb:Revision>
				V1 : 2014-09-30 : Creation
				V2 : 2014-12-01 : Technology ; Rationale ; LongDesc
			</hb:Revision>
		</hb:RuleHist>
		<hb:RuleContent>
			<hb:Name>Name of reset signal</hb:Name>
			<hb:IsParent>false</hb:IsParent>
			<hb:IsSon>true</hb:IsSon>
			<hb:ParentUID>STD_00100</hb:ParentUID>
			<hb:Technology>VLSI</hb:Technology>
			<hb:ApplicationFields>General</hb:ApplicationFields>
			<hb:Category>Formatting</hb:Category>
			<hb:SubCategory>Naming</hb:SubCategory>
			<hb:Severity>Major</hb:Severity>
			<hb:Rationale>The .</hb:Rationale>
			<hb:ShortDesc>The reset</hb:ShortDesc>
			<hb:LongDesc>A signal .</hb:LongDesc>
		</hb:RuleContent>
		<hb:Sonarqube>
			<hb:SonarType>Code_Smell</hb:SonarType>
			<hb:SonarSeverity>Blocker</hb:SonarSeverity>
			<hb:RemediationEffort>Easy</hb:RemediationEffort>
			<hb:SonarTag>Confusing</hb:SonarTag>
		</hb:Sonarqube>
		<hb:RuleDesc>
			<hb:GoodExDesc>Extracted from STD_00300_good.vhd</hb:GoodExDesc>
			<hb:GoodExample >STD_00300_good</hb:GoodExample>
			<hb:BadExDesc></hb:BadExDesc>
			<hb:BadExample ></hb:BadExample>
			<hb:FigureDesc />
			<hb:Figure />
		</hb:RuleDesc>
		<hb:RuleParams>
			<hb:StringParam>
				<hb:ParamID>P1</hb:ParamID>
				<hb:Position>Contain</hb:Position>
				<hb:Value>reset</hb:Value>
			</hb:StringParam>
			<hb:StringParam>
				<hb:ParamID>P2</hb:ParamID>
				<hb:Position>Contain</hb:Position>
				<hb:Value>rst</hb:Value>
			</hb:StringParam>
			<hb:StringParam>
				<hb:ParamID>P3</hb:ParamID>
				<hb:Position>Contain</hb:Position>
				<hb:Value>clr</hb:Value>
			</hb:StringParam>
		</hb:RuleParams>
	</hb:Rule>
	
	<hb:RuleSetHist>
		<hb:Version>5</hb:Version>
		<hb:Creation>2014-09-30</hb:Creation>
		<hb:Modified>2017-11-24</hb:Modified>
		<hb:Revision>V1 : 2014-11-13 : Creation.
V2   : 2014-12-01 : Update of rules with remarks from partners about V1 revision, rules have been transferred to CNES handbook.
V3   : 2015-02-17 : Update of rules with remarks from partners about V2 revision
V4   : 2015-07-16 : Update of rules with examples
V4.1 : 2015-11-18 : Correct several data from remarks
V5   : 2017-11-24 : Creation of Sonarqube data and update of some status
		</hb:Revision>
	</hb:RuleSetHist>	
</hb:RuleSet>

=== Facquet/VHDL-RC/sonar-vhdlrc-plugin/src/test/parameters/string_param.xml
<?xml version="1.0" encoding="UTF-8"?>
<hb:RuleSet xmlns:hb="HANDBOOK"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="HANDBOOK ../XSD/handbook.xsd ">
	
		<hb:RuleParams>
			<hb:StringParam>
				<hb:ParamID>P1</hb:ParamID>
				<hb:Position>Contain</hb:Position>
				<hb:Value>reset</hb:Value>
			</hb:StringParam>
			<hb:StringParam>
				<hb:ParamID>P2</hb:ParamID>
				<hb:Position>Prefix</hb:Position>
				<hb:Value>rst</hb:Value>
			</hb:StringParam>
			<hb:StringParam>
				<hb:ParamID>P3</hb:ParamID>
				<hb:Position>Suffix</hb:Position>
				<hb:Value>clr</hb:Value>
			</hb:StringParam>
		</hb:RuleParams>
</hb:RuleSet>

=== Facquet/VHDL-RC/sonar-vhdlrc-plugin/src/test/parameters/int_param.xml
<?xml version="1.0" encoding="UTF-8"?>
<hb:RuleSet xmlns:hb="HANDBOOK" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="HANDBOOK ../XSD/handbook.xsd ">
	<hb:RuleParams>
		<hb:IntParam>
			<hb:ParamID>P1</hb:ParamID>
			<hb:Relation>GT</hb:Relation>
			<hb:Value>8</hb:Value>
		</hb:IntParam>
		<hb:IntParam>
			<hb:ParamID>P2</hb:ParamID>
			<hb:Relation>LET</hb:Relation>
			<hb:Value>-5</hb:Value>
		</hb:IntParam>
	</hb:RuleParams>	
</hb:RuleSet>

=== Facquet/VHDL-RC/sonar-vhdlrc-plugin/src/test/parameters/hbs/handbook_range_param.xml
<?xml version="1.0" encoding="UTF-8"?>
<hb:RuleSet xmlns:hb="HANDBOOK"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="HANDBOOK ../XSD/handbook.xsd ">

		<hb:Rule UID="STD_04600">
		<hb:RuleUID>STD_04600</hb:RuleUID>
		<hb:RuleHist>
			<hb:Status>Active</hb:Status>
			<hb:Version>4</hb:Version>
			<hb:Creation>2014-09-30</hb:Creation>
			<hb:Modified>2017-11-24</hb:Modified>
			<hb:Revision>
				V1 : 2014-09-30 : Creation
			</hb:Revision>
		</hb:RuleHist>
		<hb:RuleContent>
			<hb:Name>Clock domain number in the design</hb:Name>
			<hb:IsParent>false</hb:IsParent>
			<hb:IsSon>false</hb:IsSon>
			<hb:ParentUID xsi:nil="true" />
			<hb:Technology>FPGA</hb:Technology>
			<hb:ApplicationFields>General</hb:ApplicationFields>
			<hb:Category>Design</hb:Category>
			<hb:SubCategory>Clocking</hb:SubCategory>
			<hb:Severity>Minor</hb:Severity>
			<hb:Rationale>R.</hb:ShortDesc>
			<hb:LongDesc>Tn.</hb:LongDesc>
		</hb:RuleContent>
		<hb:Sonarqube>
			<hb:SonarType>Code_Smell</hb:SonarType>
			<hb:SonarSeverity>Critical</hb:SonarSeverity>
			<hb:RemediationEffort>Complex</hb:RemediationEffort>
			<hb:SonarTag>Suspicious</hb:SonarTag>
		</hb:Sonarqube>
		<hb:RuleDesc>
			<hb:GoodExDesc></hb:GoodExDesc>
			<hb:GoodExample />
			<hb:BadExDesc></hb:BadExDesc>
			<hb:BadExample />
			<hb:FigureDesc />
			<hb:Figure fileref="STD_04600.svg" height="450px"
				width="450px" />
		</hb:RuleDesc>
		<hb:RuleParams>
			<hb:RangeParam>
				<hb:ParamID>P1</hb:ParamID>
				<hb:Range>LT_GT</hb:Range>
				<hb:ValueMin>5</hb:ValueMin>
				<hb:ValueMax>10</hb:ValueMax>
			</hb:RangeParam>
		</hb:RuleParams>
	</hb:Rule>
	
	<hb:Rule UID="STD_04700">
		<hb:RuleUID>STD_04700</hb:RuleUID>
		<hb:RuleHist>
			<hb:Status>Active</hb:Status>
			<hb:Version>4</hb:Version>
			<hb:Creation>2014-09-30</hb:Creation>
			<hb:Modified>2017-11-24</hb:Modified>
			<hb:Revision>
				V1 : 2014-09-30 : Creation
				V2 : 2014-12-01 : LongDesc
			</hb:Revision>
		</hb:RuleHist>
		<hb:RuleContent>
			<hb:Name>Number of clock domains per modules</hb:Name>
			<hb:IsParent>false</hb:IsParent>
			<hb:IsSon>false</hb:IsSon>
			<hb:ParentUID xsi:nil="true" />
			<hb:Technology>FPGA</hb:Technology>
			<hb:ApplicationFields>General</hb:ApplicationFields>
			<hb:Category>Design</hb:Category>
			<hb:SubCategory>Clocking</hb:SubCategory>
			<hb:Severity>Minor</hb:Severity>
			<hb:Rationale> the clock .</hb:Rationale>
			<hb:ShortDesc>Each .</hb:ShortDesc>
			<hb:LongDesc>Entity </hb:LongDesc>
		</hb:RuleContent>
		<hb:Sonarqube>
			<hb:SonarType>Code_Smell</hb:SonarType>
			<hb:SonarSeverity>Critical</hb:SonarSeverity>
			<hb:RemediationEffort>High</hb:RemediationEffort>
			<hb:SonarTag>Suspicious</hb:SonarTag>
		</hb:Sonarqube>
		<hb:RuleDesc>
			<hb:GoodExDesc></hb:GoodExDesc>
			<hb:GoodExample />
			<hb:BadExDesc></hb:BadExDesc>
			<hb:BadExample />
			<hb:FigureDesc />
			<hb:Figure />
		</hb:RuleDesc>
		<hb:RuleParams>
			<hb:RangeParam>
				<hb:ParamID>P1</hb:ParamID>
				<hb:Range>LET_GT</hb:Range>
				<hb:ValueMin>-5</hb:ValueMin>
				<hb:ValueMax>10050</hb:ValueMax>
			</hb:RangeParam>
		</hb:RuleParams>
	</hb:Rule>
	
	
	<hb:RuleSetHist>
		<hb:Version>5</hb:Version>
		<hb:Creation>2014-09-30</hb:Creation>
		<hb:Modified>2017-11-24</hb:Modified>
		<hb:Revision>V1 : 2014-11-13 : Creation.
V2   : 2014-12-01 : Update of rules with remarks from partners about V1 revision, rules have been transferred to CNES handbook.
V3   : 2015-02-17 : Update of rules with remarks from partners about V2 revision
V4   : 2015-07-16 : Update of rules with examples
V4.1 : 2015-11-18 : Correct several data from remarks
V5   : 2017-11-24 : Creation of Sonarqube data and update of some status
		</hb:Revision>
	</hb:RuleSetHist>	
</hb:RuleSet>
